### ISSUE TITLE
Ez alatt a kommentár alatt mire gondoltál?

### ISSUE THREAD

**Issue by csorbakristof** [bmeaut/grainautline#109]
diff --git a/MarbleCommon/BlobsAndCurves/ProcessingStateDescriptor.h b/MarbleCommon/BlobsAndCurves/ProcessingStateDescriptor.h
index a707511..55263b2 100644
--- a/MarbleCommon/BlobsAndCurves/ProcessingStateDescriptor.h
+++ b/MarbleCommon/BlobsAndCurves/ProcessingStateDescriptor.h
@@ -17,6 +17,9 @@ public:
    /*\* Loads from a file created by Save(). */
     explicit ProcessingStateDescriptor(std::string filename);

Mivel másolás történik az std::async hívásoknál, illetve fordítótól függően a SlotManager.cpp:145-ben,
így érdemes explicite kiírni, hogy a másoló konstruktor az alapértelmezett, hogy még véletlenül se
higgye azt senki, hogy a setId() ott is növel.

**Comment by szotsaki** [comment]
Mindössze egy `ProcessingStateDescriptor(const ProcessingStateDescriptor& other) = default;` deklarálást, hogy az egyszeri ember, aki a PSD kódja felé téved, lássa, hogy másolásnál szándékosan nincs ID növelgetés és nem csak lemaradt.

**Comment by szotsaki** [comment]
Fixed in 0d62bcf6ba7fa61e5078da8a1550071bb14547b8.
