### ISSUE TITLE
ImageBlender::AddImage crashes when opening a new file

### ISSUE THREAD

**Issue by szotsaki** [bmeaut/grainautline#31]
1. Open a small file
2. Run the Adts processor on it with default settings
3. Open a big file

Exception occurs saying:

```
[Debug] AdtsProcessor::Step [AdtsProcessor.cpp:12]
[Debug] AdtsLayer::Render: updating cache [AdtsLayer.cpp:28]
OpenCV Error: Internal error (Added images must have the same size.) in ImageBlender::AddImage, file ../../MarbleCommon/ImageBlender.cpp, line 29
terminate called after throwing an instance of 'cv::Exception'
  what():  ../../MarbleCommon/ImageBlender.cpp:29: error: (-3) Added images must have the same size. in function ImageBlender::AddImage
```

**Comment by csorbakristof** [comment]
AdtsLayer is not rendered after opening a new image (as the AdtsProcessor is not run immediately), so the ImageProvider cache keeps the previous processing result image for the AdtsLayer, which has a different image size, so the FlattenImage fails an assert (which checks the equal size of all layer images).

We need a mechanism to notify processors, layers and the ImageProvider that the user opened a new file.

**Comment by szotsaki** [comment]
Foundation work in d1f6b6ccf9a3f70f4abf160182c7361356c5452b.

**Comment by csorbakristof** [comment]
Now it works, closing...
