### ISSUE TITLE
Make GrainAutLine compile with both GCC and MSVC

### ISSUE THREAD

**Issue by szotsaki** [bmeaut/grainautline#87]
1.) Install Qt both with mingw32 and msvc-$(latest) support.
2.) Install Visual Studio Express $(latest).
3.) Compile GrainAutline and its test suite with the GCC toolchain from Qt Creator.
4.) Compile GrainAutline and its test suite with the MSVC toolchain from Qt Creator.
5.) Make Jenkins run these compilations automatically after each commit to the master (or dev) branch.

**Comment by csorbakristof** [comment]
(Finishing Sonar and setting up the AUT department Jenkins is more important than the MSVC toolchain, so that should be the last task of the semester.)

**Comment by csorbakristof** [comment]
done
